### ISSUE TITLE
Update caffe ?

### ISSUE THREAD

**Issue by bermanmaxim** [shubhtuls/ViewpointsAndKeypoints#1]
Hello, 

I would like to train the networks here but I would need to use the `iter_size` options available on newer versions of caffe in order to make the training fit my limited GPU memory... Is there any chance you could either update your modified version of caffe or provide the trained network snapshots with the release for easier result reproduction ?

Thanks!

**Comment by shubhtuls** [comment]
I think it might be easiest for me to release the trained models. The viewpoint prediction model (for all 3 angles) can be found [here](http://www.cs.berkeley.edu/~shubhtuls/cachedir/vpsKps/vggJointVps.caffemodel). Please let me know if you require the keypoint prediction model. If you would like to train the viewpoint prediction model on your end, I can work on releasing a cleaner python version of code but that might take longer.

**Comment by bermanmaxim** [comment]
Thanks for the trained model; that makes it much easier. If possible I would indeed be interested by the keypoint model as well. Best

**Comment by shubhtuls** [comment]
There are two keypoint prediction models for different scales ([6 X 6](http://www.cs.berkeley.edu/~shubhtuls/cachedir/vpsKps/vggConv6Kps.caffemodel) and [12 X 12](http://www.cs.berkeley.edu/~shubhtuls/cachedir/vpsKps/vggConv12Kps.caffemodel)).

**Comment by bermanmaxim** [comment]
Allright ; thanks a lot for the trained Caffemodels.
