### ISSUE TITLE
I meet one trouble...

### ISSUE THREAD

**Issue by Scsy** [shubhtuls/ViewpointsAndKeypoints#6]
Hi! @shubhtuls  
I follow the readme, and when I run mainVpsPridet, it's requires ilsvrc_2012_mean.mat, but i didn't see this mat in /external/caffe/matlab/caffe/. Can you tell me how to solve this?
Thanks!

**Comment by shubhtuls** [comment]
Sorry about the issue, perhaps you could download it from [here](https://github.com/shubhtuls/caffePose/blob/master/matlab/%2Bcaffe/imagenet/ilsvrc_2012_mean.mat) and store it where needed.

**Comment by Scsy** [comment]
Thanks！
